-- EXEC sp_rename 'funandgames.dbo.player.PlayerID', 'playerID', 'COLUMN';
-- EXEC sp_rename 'funandgames.dbo.player.First_Name', 'first_name', 'COLUMN';
-- EXEC sp_rename 'funandgames.dbo.player.Surname', 'surname', 'COLUMN';
-- EXEC sp_rename 'funandgames.dbo.player.Home_City', 'home_city', 'COLUMN';
-- EXEC sp_rename 'funandgames.dbo.player.University', 'university', 'COLUMN';
-- EXEC sp_rename 'funandgames.dbo.player.Degree', 'degree', 'COLUMN';
-- EXEC sp_rename 'funandgames.dbo.player.LorR', 'lorr', 'COLUMN';
-- EXEC sp_rename 'funandgames.dbo.player.DOB', 'dob', 'COLUMN';